import pandas as pd

def calculate_player_contribution(player_df, team_df):
    """
    Merges player and team data and calculates a player's contribution to team stats.

    Args:
        player_df (pd.DataFrame): The processed player data.
        team_df (pd.DataFrame): The processed team data.

    Returns:
        pd.DataFrame: A new DataFrame with player contribution metrics.
    """
    if player_df is None or team_df is None:
        print("Error: Input DataFrames are not valid.")
        return None

    print("\nCalculating player contribution to team stats...")

    # Define a small epsilon to avoid division by zero
    epsilon = 1e-6

    # Team name mapping for consistent naming across both datasets
    TEAM_NAME_MAP = {
        'Ben': 'Bengaluru Bulls',
        'Beng': 'Bengal Warriors',
        'Dab': 'Dabang Delhi K.C.',
        'Guj': 'Gujarat Fortunegiants',
        'Hyd': 'Telugu Titans',
        'Jai': 'Jaipur Pink Panthers',
        'Jaipur': 'Jaipur Pink Panthers',
        'Pat': 'Patna Pirates',
        'Pun': 'Puneri Paltan',
        'Tamil': 'Tamil Thalaivas',
        'U Mumba': 'U Mumba',
        'UP Yoddha': 'U.P. Yoddha',
        'Ben, Mum': 'Bengaluru Bulls',  # Handling specific inconsistency found
        'Kol': 'Kolkata' # Added a dummy mapping since 'Kol' existed in the json and not in the csv
    }
    
    # Standardize team names in both DataFrames to ensure a successful merge
    player_df['team_name'] = player_df['team_name'].str.strip().replace(TEAM_NAME_MAP)
    team_df['team_name'] = team_df['team_name'].str.strip().replace(TEAM_NAME_MAP)

    # Check if essential columns exist before attempting the merge
    required_player_cols = ['team_name', 'season', 'total_points', 'raid_points', 'tackle_points', 'do_or_die_points', 'successful_raids', 'successful_tackles', 'super_raids', 'super_tackles']
    required_team_cols = ['team_name', 'season', 'points_scored', 'raid_points', 'tackle_points', 'do_or_die_points', 'successful_raids', 'successful_tackles', 'super_raids', 'super_tackles']
    
    if not all(col in player_df.columns for col in required_player_cols):
        print("Error: Missing required columns in player data. Please check 'processed_kabaddi_stats.csv'.")
        return None
    
    if not all(col in team_df.columns for col in required_team_cols):
        print("Error: Missing required columns in team data. Please check 'processed_kabaddi_teams_stats.csv'.")
        return None
        
    # Merge the two dataframes on team_name and season, which are the correct keys
    merged_df = pd.merge(player_df, team_df, on=['team_name', 'season'], suffixes=('_player', '_team'), how='inner')

    # Check if the merged DataFrame is empty
    if merged_df.empty:
        print("Warning: The merged DataFrame is empty. This means no matching player and team data was found after cleaning. Please check team names and seasons in your CSV files.")
        return None
    
    # Calculate contribution for key metrics
    merged_df['raid_points_contribution'] = merged_df['raid_points_player'] / (merged_df['raid_points_team'] + epsilon)
    merged_df['tackle_points_contribution'] = merged_df['tackle_points_player'] / (merged_df['tackle_points_team'] + epsilon)
    merged_df['total_points_contribution'] = merged_df['total_points_player'] / (merged_df['points_scored_team'] + epsilon)

    # Add new contribution calculations based on the provided column names
    merged_df['do_or_die_points_contribution'] = merged_df['do_or_die_points_player'] / (merged_df['do_or_die_points_team'] + epsilon)
    merged_df['successful_raids_contribution'] = merged_df['successful_raids_player'] / (merged_df['successful_raids_team'] + epsilon)
    merged_df['successful_tackles_contribution'] = merged_df['successful_tackles_player'] / (merged_df['successful_tackles_team'] + epsilon)
    merged_df['super_raids_contribution'] = merged_df['super_raids_player'] / (merged_df['super_raids_team'] + epsilon)
    merged_df['super_tackles_contribution'] = merged_df['super_tackles_player'] / (merged_df['super_tackles_team'] + epsilon)

    # Filter for the relevant columns to create the final output DataFrame
    contribution_df = merged_df[[
        'player_name', 'team_name', 'season', 'position_name',
        'raid_points_player', 'tackle_points_player', 'total_points_player',
        'raid_points_contribution', 'tackle_points_contribution', 'total_points_contribution',
        'do_or_die_points_contribution', 'successful_raids_contribution',
        'successful_tackles_contribution', 'super_raids_contribution',
        'super_tackles_contribution'
    ]]

    # Save the new DataFrame to a CSV file
    contribution_df.to_csv('player_contribution_stats.csv', index=False)
    print("Successfully calculated and saved player contribution stats to 'player_contribution_stats.csv'.")
    return contribution_df

if __name__ == "__main__":
    try:
        # Load the two CSV files generated by the previous script
        player_df = pd.read_csv('processed_kabaddi_stats.csv')
        team_df = pd.read_csv('processed_kabaddi_teams_stats.csv')

        # Clean column names by stripping whitespace
        player_df.columns = player_df.columns.str.strip()
        team_df.columns = team_df.columns.str.strip()

        # Calculate the player contribution
        player_contribution_df = calculate_player_contribution(player_df, team_df)

        if player_contribution_df is not None:
            print("\nFinal Processed Player Contribution DataFrame:")
            print(player_contribution_df.head())
    
    except FileNotFoundError as e:
        print(f"Error: One or more CSV files were not found. Please ensure 'processed_kabaddi_stats.csv' and 'processed_kabaddi_teams_stats.csv' exist in the current directory.")
        print(f"Details: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
